# Generated by Django 4.1.7 on 2023-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_alter_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Цвет тега"
            ),
        ),
    ]
