# Generated by Django 4.1.7 on 2023-03-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_alter_tag_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="recipe.tag", verbose_name="Теги рецепта"
            ),
        ),
    ]
