# Generated by Django 4.1.7 on 2023-03-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_remove_recipe_tags_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipe.tag",
                verbose_name="Теги рецепта",
            ),
            preserve_default=False,
        ),
    ]
