# Generated by Django 4.1.7 on 2023-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_remove_recipe_tags_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="recipe.tag", verbose_name="Теги рецепта"
            ),
        ),
    ]
