# Generated by Django 4.1.7 on 2023-03-13 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0007_alter_ingredientunits_ingredients_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredientunits",
            old_name="ingredients",
            new_name="ingredient",
        ),
    ]
